
version: '2.3'
services:
    api:
        build: .
        restart: unless-stopped
        depends_on:
            - redis
        ports:
            - 9080:8080
        environment:
            REDIS_CONNECTION: redis://redis:6379/1

    redis:
        image: redis:alpine
        restart: unless-stopped
        volumes:
            - ./storage/redis/data:/data
        ports:
            - 6389:6379
volumes:
    redis: